"""Rebuild the pinned Material Symbols subset (fonttools==4.59.0).

Source downloads stay in Artifacts; the static TTF, provenance and generated
semantic C++ mapping are checked in. Normal Editor builds do not run this tool.
"""
from pathlib import Path
import hashlib
import json
import urllib.request

import fontTools
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / 'Resources/Editor/Fonts'
CACHE = ROOT / 'Artifacts/phase21-material-symbols/upstream'
SPEC = json.loads((DEST / 'MaterialSymbols.json').read_text(encoding='utf-8'))
BASE = f'https://raw.githubusercontent.com/google/material-design-icons/{SPEC["source_commit"]}/'
STEM = 'variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D'


def source(relative, filename):
    path = CACHE / filename
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        request = urllib.request.Request(BASE + relative, headers={'User-Agent': 'CreatorEngine-Fonts'})
        path.write_bytes(urllib.request.urlopen(request, timeout=120).read())
    return path


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    assert fontTools.__version__ == SPEC['fonttools_version']
    original = source(STEM + '.ttf', 'MaterialSymbolsOutlined.ttf')
    codepoints = source(STEM + '.codepoints', 'MaterialSymbolsOutlined.codepoints')
    license_file = source('LICENSE', 'LICENSE.txt')
    names = {name: int(cp, 16) for name, cp in
             (line.split() for line in codepoints.read_text().splitlines())}
    roles = [(role, name, names[name]) for role, name in SPEC['roles'].items()]
    points = sorted({cp for _, _, cp in roles})
    assert all(0xE000 <= cp <= 0xF8FF for cp in points)

    font = TTFont(original, recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = []  # ImGui consumes codepoints, never ligatures/ASCII.
    options.name_IDs = ['*']
    options.name_legacy = True
    options.name_languages = ['*']
    sub = subset.Subsetter(options)
    sub.populate(unicodes=points)
    sub.subset(font)
    assert set(SPEC['axes']) == {axis.axisTag for axis in font['fvar'].axes}
    font = instantiateVariableFont(font, SPEC['axes'], inplace=True)
    output = DEST / 'MaterialSymbolsOutlined-Editor.ttf'
    font.save(output)
    verified = TTFont(output)
    assert 'fvar' not in verified and set(verified.getBestCmap()) == set(points)
    (DEST / 'LICENSE-MaterialSymbols.txt').write_bytes(license_file.read_bytes())

    header = ['#pragma once', '// Generated by Tools/fonts/build-editor-symbol-font.py; edit MaterialSymbols.json.',
              '#include <array>', '#include <cstddef>', '', 'namespace EditorIcon', '{',
              '    inline constexpr const char* FontPath = "Fonts/MaterialSymbolsOutlined-Editor.ttf";',
              '    inline constexpr const char* Family = "Material Symbols Outlined";', '']
    for role, name, cp in roles:
        utf8 = ''.join(f'\\x{value:02x}' for value in chr(cp).encode('utf-8'))
        header.append(f'    inline constexpr char {role}[] = "{utf8}"; // {name}, U+{cp:04X}')
    header += ['', '    struct Role { const char* name; const char* symbol; unsigned int codepoint; };',
               '    inline constexpr Role Roles[] = {']
    header += [f'        {{ "{role}", "{name}", 0x{cp:04x} }},' for role, name, cp in roles]
    header += ['    };', '', '    // Static storage: composed labels never point into a temporary string.',
               '    template<std::size_t N> struct Text', '    {', '        char value[N]{};',
               '        consteval Text(const char (&text)[N])', '        {',
               '            for (std::size_t i = 0; i < N; ++i) value[i] = text[i];', '        }', '    };',
               '    template<const auto& Icon, Text Suffix>', '    inline constexpr auto LabelStorage = []', '    {',
               '        std::array<char, sizeof(Icon) + sizeof(Suffix.value) - 1> result{};',
               '        for (std::size_t i = 0; i + 1 < sizeof(Icon); ++i) result[i] = Icon[i];',
               '        for (std::size_t i = 0; i < sizeof(Suffix.value); ++i)',
               '            result[sizeof(Icon) - 1 + i] = Suffix.value[i];',
               '        return result;', '    }();',
               '    template<const auto& Icon, Text Suffix>',
               '    inline constexpr const char* Label = LabelStorage<Icon, Suffix>.data();', '}', '']
    (ROOT / 'Editor/ImGuiHelper/EditorIcons.h').write_text('\n'.join(header), encoding='utf-8')
    provenance = dict(source_url=BASE + STEM + '.ttf', source_sha256=digest(original),
                      codepoints_url=BASE + STEM + '.codepoints', codepoints_sha256=digest(codepoints),
                      license_url=BASE + 'LICENSE', license_sha256=digest(license_file),
                      font_sha256=digest(output), font_bytes=output.stat().st_size,
                      axes=SPEC['axes'], fonttools_version=fontTools.__version__,
                      role_count=len(roles), glyph_count=len(points))
    (DEST / 'MaterialSymbols.provenance.json').write_text(json.dumps(provenance, indent=2) + '\n')
    print(json.dumps(provenance, indent=2), flush=True)


if __name__ == '__main__':
    main()
