// Generated by Tools/blender/export-lx-material-schema.ps1 from the pinned Blender 5.1.1 socket fixture.
#include "LXMaterialOperators.h"

#include <stdexcept>

namespace LX
{
namespace
{
void Register(LXMaterialDefinitions& result, LXNodeDefinitionRegistry& registry, NodeSpec spec,
              LXMaterialNodeSchema schema)
{
    const auto type = spec.type;
    std::string error;
    if (!registry.Register({"material", std::move(spec)}, &error))
    {
        throw std::logic_error(error);
    }
    result.schemas.emplace(type, std::move(schema));
}
} // namespace

LXMaterialDefinitions CreateMaterialDefinitions()
{
    LXMaterialDefinitions result;
    auto registry = std::make_shared<LXNodeDefinitionRegistry>();
    {
        NodeSpec spec;
        spec.type = "ShaderNodeRGB";
        spec.title = "Color";
        LXMaterialNodeSchema schema;
        spec.pins.push_back({0, 0, "Color", Direction::Output, PinType::Color, false, false, "Color",
                             std::array<double, 4>{0.5, 0.5, 0.5, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        Register(result, *registry, std::move(spec), std::move(schema));
    }
    {
        NodeSpec spec;
        spec.type = "ShaderNodeValue";
        spec.title = "Value";
        LXMaterialNodeSchema schema;
        spec.pins.push_back({0, 0, "Value", Direction::Output, PinType::Float, false, false, "Value", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        Register(result, *registry, std::move(spec), std::move(schema));
    }
    {
        NodeSpec spec;
        spec.type = "ShaderNodeTexImage";
        spec.title = "Image Texture";
        LXMaterialNodeSchema schema;
        spec.pins.push_back({0, 0, "Vector", Direction::Input, PinType::Vector, false, false, "Vector",
                             std::array<double, 3>{0.0, 0.0, 0.0}});
        schema.sockets.push_back({true, false, true, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Color", Direction::Output, PinType::Color, false, false, "Color",
                             std::array<double, 4>{0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        spec.pins.push_back({0, 0, "Alpha", Direction::Output, PinType::Float, false, false, "Alpha", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.properties = {{"image", ""},
                           {"colorSpace", "srgb"},
                           {"interpolation", "Linear"},
                           {"extension", "REPEAT"},
                           {"projection", "FLAT"}};
        schema.enumProperties = {{"colorSpace", {"data", "linear", "srgb"}},
                                 {"interpolation", {"Linear", "Closest", "Cubic", "Smart"}},
                                 {"extension", {"REPEAT", "EXTEND", "CLIP", "MIRROR"}},
                                 {"projection", {"FLAT", "BOX", "SPHERE", "TUBE"}}};
        Register(result, *registry, std::move(spec), std::move(schema));
    }
    {
        NodeSpec spec;
        spec.type = "ShaderNodeNormalMap";
        spec.title = "Normal Map";
        LXMaterialNodeSchema schema;
        spec.pins.push_back({0, 0, "Strength", Direction::Input, PinType::Float, false, false, "Strength", 1.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Color", Direction::Input, PinType::Color, false, false, "Color",
                             std::array<double, 4>{0.5, 0.5, 1.0, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        spec.pins.push_back({0, 0, "Normal", Direction::Output, PinType::Vector, false, false, "Normal",
                             std::array<double, 3>{0.0, 0.0, 0.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.properties = {{"space", "TANGENT"}, {"uvMap", ""}};
        schema.enumProperties = {{"space", {"TANGENT", "OBJECT", "WORLD", "BLENDER_OBJECT", "BLENDER_WORLD"}}};
        Register(result, *registry, std::move(spec), std::move(schema));
    }
    {
        NodeSpec spec;
        spec.type = "ShaderNodeBsdfPrincipled";
        spec.title = "Principled BSDF";
        LXMaterialNodeSchema schema;
        spec.pins.push_back({0, 0, "Base Color", Direction::Input, PinType::Color, false, false, "Base Color",
                             std::array<double, 4>{0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        spec.pins.push_back({0, 0, "Metallic", Direction::Input, PinType::Float, false, false, "Metallic", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Roughness", Direction::Input, PinType::Float, false, false, "Roughness", 0.5});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "IOR", Direction::Input, PinType::Float, false, false, "IOR", 1.5});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Alpha", Direction::Input, PinType::Float, false, false, "Alpha", 1.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Normal", Direction::Input, PinType::Vector, false, false, "Normal",
                             std::array<double, 3>{0.0, 0.0, 0.0}});
        schema.sockets.push_back({true, false, true, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Weight", Direction::Input, PinType::Float, false, false, "Weight", 0.0});
        schema.sockets.push_back({false, false, false, LXColorSpace::Data});
        spec.pins.push_back(
            {0, 0, "Diffuse Roughness", Direction::Input, PinType::Float, false, false, "Diffuse Roughness", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back(
            {0, 0, "Subsurface Weight", Direction::Input, PinType::Float, false, false, "Subsurface Weight", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Subsurface Radius", Direction::Input, PinType::Vector, false, false,
                             "Subsurface Radius",
                             std::array<double, 3>{1.0, 0.20000000298023224, 0.10000000149011612}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Subsurface Scale", Direction::Input, PinType::Float, false, false,
                             "Subsurface Scale", 0.05000000074505806});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Subsurface IOR", Direction::Input, PinType::Float, false, false, "Subsurface IOR",
                             1.399999976158142});
        schema.sockets.push_back({false, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Subsurface Anisotropy", Direction::Input, PinType::Float, false, false,
                             "Subsurface Anisotropy", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back(
            {0, 0, "Specular IOR Level", Direction::Input, PinType::Float, false, false, "Specular IOR Level", 0.5});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Specular Tint", Direction::Input, PinType::Color, false, false, "Specular Tint",
                             std::array<double, 4>{1.0, 1.0, 1.0, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        spec.pins.push_back({0, 0, "Anisotropic", Direction::Input, PinType::Float, false, false, "Anisotropic", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Anisotropic Rotation", Direction::Input, PinType::Float, false, false,
                             "Anisotropic Rotation", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Tangent", Direction::Input, PinType::Vector, false, false, "Tangent",
                             std::array<double, 3>{0.0, 0.0, 0.0}});
        schema.sockets.push_back({true, false, true, LXColorSpace::Data});
        spec.pins.push_back(
            {0, 0, "Transmission Weight", Direction::Input, PinType::Float, false, false, "Transmission Weight", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Coat Weight", Direction::Input, PinType::Float, false, false, "Coat Weight", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Coat Roughness", Direction::Input, PinType::Float, false, false, "Coat Roughness",
                             0.029999999329447746});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Coat IOR", Direction::Input, PinType::Float, false, false, "Coat IOR", 1.5});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Coat Tint", Direction::Input, PinType::Color, false, false, "Coat Tint",
                             std::array<double, 4>{1.0, 1.0, 1.0, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        spec.pins.push_back({0, 0, "Coat Normal", Direction::Input, PinType::Vector, false, false, "Coat Normal",
                             std::array<double, 3>{0.0, 0.0, 0.0}});
        schema.sockets.push_back({true, false, true, LXColorSpace::Data});
        spec.pins.push_back(
            {0, 0, "Sheen Weight", Direction::Input, PinType::Float, false, false, "Sheen Weight", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back(
            {0, 0, "Sheen Roughness", Direction::Input, PinType::Float, false, false, "Sheen Roughness", 0.5});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Sheen Tint", Direction::Input, PinType::Color, false, false, "Sheen Tint",
                             std::array<double, 4>{1.0, 1.0, 1.0, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        spec.pins.push_back({0, 0, "Emission Color", Direction::Input, PinType::Color, false, false, "Emission Color",
                             std::array<double, 4>{1.0, 1.0, 1.0, 1.0}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Linear});
        spec.pins.push_back(
            {0, 0, "Emission Strength", Direction::Input, PinType::Float, false, false, "Emission Strength", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back(
            {0, 0, "Thin Film Thickness", Direction::Input, PinType::Float, false, false, "Thin Film Thickness", 0.0});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Thin Film IOR", Direction::Input, PinType::Float, false, false, "Thin Film IOR",
                             1.3300000429153442});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "BSDF", Direction::Output, PinType::Closure, false, false, "BSDF", {}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        Register(result, *registry, std::move(spec), std::move(schema));
    }
    {
        NodeSpec spec;
        spec.type = "ShaderNodeOutputMaterial";
        spec.title = "Material Output";
        LXMaterialNodeSchema schema;
        spec.pins.push_back({0, 0, "Surface", Direction::Input, PinType::Closure, false, false, "Surface", {}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Volume", Direction::Input, PinType::Closure, false, false, "Volume", {}});
        schema.sockets.push_back({true, false, false, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Displacement", Direction::Input, PinType::Vector, false, false, "Displacement",
                             std::array<double, 3>{0.0, 0.0, 0.0}});
        schema.sockets.push_back({true, false, true, LXColorSpace::Data});
        spec.pins.push_back({0, 0, "Thickness", Direction::Input, PinType::Float, false, false, "Thickness", 0.0});
        schema.sockets.push_back({true, false, true, LXColorSpace::Data});
        spec.properties = {{"target", "ALL"}};
        schema.enumProperties = {{"target", {"ALL", "EEVEE", "CYCLES"}}};
        Register(result, *registry, std::move(spec), std::move(schema));
    }
    // Engine resource/parameter primitives. These are not presented as Blender node definitions.
    for (PinType type : {PinType::Bool, PinType::Int, PinType::Float, PinType::Vector, PinType::Color, PinType::Normal,
                         PinType::Texture, PinType::Sampler})
    {
        NodeSpec spec;
        spec.type = std::string("LXParameter") + PinTypeName(type);
        spec.title = std::string(PinTypeName(type)) + " Parameter";
        spec.pins.push_back({0, 0, "Value", Direction::Output, type, false, false, "Value"});
        spec.properties = {{"parameter", "0"}};
        LXMaterialNodeSchema schema;
        schema.enumProperties = {{"valueSource", {"blackboard", "socket"}}};
        schema.sockets.push_back(
            {true, false, false, type == PinType::Color ? LXColorSpace::Linear : LXColorSpace::Data});
        NodeSpec reroute;
        reroute.type = std::string("LXReroute") + PinTypeName(type);
        reroute.title = "Reroute";
        reroute.pins = {{0, 0, "Input", Direction::Input, type, false, false, "Input"},
                        {0, 0, "Output", Direction::Output, type, false, false, "Output"}};
        LXMaterialNodeSchema rerouteSchema;
        rerouteSchema.sockets = {schema.sockets.front(), schema.sockets.front()};
        Register(result, *registry, std::move(spec), std::move(schema));
        Register(result, *registry, std::move(reroute), std::move(rerouteSchema));
    }
    RegisterMaterialOperators(result, *registry);
    result.nodes = std::move(registry);
    return result;
}

} // namespace LX
