"""Mirror the canonical Slang LUT into the SceneLookup b1 float4 layout."""
import argparse
from pathlib import Path
import re

root = Path(__file__).resolve().parents[2]
source = root / "Dynamic_CPP/Assets/Shaders/DefaultPassShader/Includes/PrincipledThinFilmSensitivity.slang"
target = root / "Engine/RenderEngine/MaterialGraphThinFilmSensitivity.h"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
text = source.read_text(encoding="utf-8-sig")
rows = []
for name in ("FilmSensitivityReal", "FilmSensitivityImag"):
    body = re.search(r"static const float3 " + name + r"\[512\]\s*=\s*\{(.*?)\};", text, re.S)
    if body is None:
        raise ValueError("Missing canonical table: " + name)
    values = re.findall(r"float3\(([^)]*)\)", body[1])
    if len(values) != 512:
        raise ValueError("Expected 512 rows: " + name)
    for value in values:
        components = [v.strip() for v in value.split(",")]
        if len(components) != 3:
            raise ValueError("Invalid table row")
        rows.append("    " + ", ".join(v + "f" for v in components) + ", 0.0f,")
generated = "\n".join([
    "#pragma once",
    "// Generated by Tools/regression/generate-film-sensitivity-upload.py.",
    "// Canonical values and attribution: PrincipledThinFilmSensitivity.slang.",
    "// XYZ CMF data: Copyright 2011-2025 Blender Foundation, Apache-2.0.",
    "// See Tools/blender/fixtures/thin-film-sensitivity-5.1.1/NOTICE.md.",
    "#include <array>",
    "namespace material_graph {",
    "inline constexpr std::array<float, 4096> kFilmSensitivityConstants{", *rows,
    "};", "static_assert(sizeof(kFilmSensitivityConstants) == 16384);", "}", "",
])
if args.check:
    if target.read_text(encoding="utf-8") != generated:
        raise ValueError("Sensitivity upload mirror is stale")
    print("FILM_SENSITIVITY_UPLOAD_OK rows=1024 bytes=16384")
else:
    target.write_text(generated, encoding="utf-8")
