#pragma once
// Generated by Tools/fonts/build-editor-symbol-font.py; edit MaterialSymbols.json.
#include <array>
#include <cstddef>

namespace EditorIcon
{
    inline constexpr const char* FontPath = "Fonts/MaterialSymbolsOutlined-Editor.ttf";
    inline constexpr const char* Family = "Material Symbols Outlined";

    inline constexpr char Scene[] = "\xee\xbf\x89"; // view_in_ar, U+EFC9
    inline constexpr char Game[] = "\xee\xa8\xa8"; // sports_esports, U+EA28
    inline constexpr char Hierarchy[] = "\xee\xa5\xba"; // account_tree, U+E97A
    inline constexpr char Inspector[] = "\xee\x90\xa9"; // tune, U+E429
    inline constexpr char AssetBundle[] = "\xee\x86\xa1"; // inventory_2, U+E1A1
    inline constexpr char ContentBrowser[] = "\xee\x8b\x88"; // folder_open, U+E2C8
    inline constexpr char Select[] = "\xef\xa0\xaf"; // arrow_selector_tool, U+F82F
    inline constexpr char Move[] = "\xee\xa2\x9f"; // open_with, U+E89F
    inline constexpr char Rotate[] = "\xee\x90\x9a"; // rotate_right, U+E41A
    inline constexpr char Scale[] = "\xef\x87\x8e"; // open_in_full, U+F1CE
    inline constexpr char Orthographic[] = "\xee\x8f\x86"; // crop_square, U+E3C6
    inline constexpr char Perspective[] = "\xee\xbf\x89"; // view_in_ar, U+EFC9
    inline constexpr char Grid[] = "\xef\x80\x96"; // grid_4x4, U+F016
    inline constexpr char Snap[] = "\xee\x8f\xac"; // grid_on, U+E3EC
    inline constexpr char Search[] = "\xee\xbd\xba"; // search, U+EF7A
    inline constexpr char Settings[] = "\xee\xa2\xb8"; // settings, U+E8B8
    inline constexpr char AvatarMask[] = "\xee\xa4\xac"; // accessibility_new, U+E92C
    inline constexpr char Add[] = "\xee\x85\x85"; // add, U+E145
    inline constexpr char Remove[] = "\xee\x85\x9b"; // remove, U+E15B
    inline constexpr char Delete[] = "\xee\xa4\xae"; // delete, U+E92E
    inline constexpr char Folder[] = "\xee\x8b\x87"; // folder, U+E2C7
    inline constexpr char GameObject[] = "\xef\x9c\xa0"; // deployed_code, U+F720
    inline constexpr char Prefab[] = "\xef\x9c\xa0"; // deployed_code, U+F720
    inline constexpr char AssetPicker[] = "\xee\x8b\x88"; // folder_open, U+E2C8
    inline constexpr char More[] = "\xee\x97\x93"; // more_horiz, U+E5D3
    inline constexpr char Back[] = "\xee\x97\x84"; // arrow_back, U+E5C4
    inline constexpr char Forward[] = "\xee\x97\x88"; // arrow_forward, U+E5C8
    inline constexpr char Up[] = "\xee\x97\x98"; // arrow_upward, U+E5D8
    inline constexpr char Down[] = "\xee\x97\x9b"; // arrow_downward, U+E5DB
    inline constexpr char Audio[] = "\xee\xae\x82"; // audio_file, U+EB82
    inline constexpr char Play[] = "\xee\x80\xb7"; // play_arrow, U+E037
    inline constexpr char Pause[] = "\xee\x80\xb4"; // pause, U+E034
    inline constexpr char Stop[] = "\xee\x81\x87"; // stop, U+E047
    inline constexpr char Debug[] = "\xee\xa1\xa8"; // bug_report, U+E868
    inline constexpr char Console[] = "\xee\xae\x8e"; // terminal, U+EB8E
    inline constexpr char Profiler[] = "\xee\x89\xab"; // bar_chart, U+E26B
    inline constexpr char Info[] = "\xee\xa2\x8e"; // info, U+E88E
    inline constexpr char Warning[] = "\xef\x82\x83"; // warning, U+F083
    inline constexpr char Error[] = "\xef\xa2\xb6"; // error, U+F8B6
    inline constexpr char Revert[] = "\xee\x85\xa6"; // undo, U+E166
    inline constexpr char Runtime[] = "\xee\x8c\xa2"; // memory, U+E322
    inline constexpr char Layers[] = "\xee\x94\xbb"; // layers, U+E53B
    inline constexpr char Tag[] = "\xef\x81\x9b"; // sell, U+F05B
    inline constexpr char Timing[] = "\xee\x90\xa5"; // timer, U+E425
    inline constexpr char Baseline[] = "\xef\x83\x86"; // flag, U+F0C6
    inline constexpr char Close[] = "\xee\x97\x8d"; // close, U+E5CD
    inline constexpr char Expand[] = "\xee\x97\x8f"; // expand_more, U+E5CF
    inline constexpr char Collapse[] = "\xee\x97\x8c"; // chevron_right, U+E5CC
    inline constexpr char Appearance[] = "\xee\x8e\xae"; // brush, U+E3AE
    inline constexpr char Camera[] = "\xee\x90\x92"; // photo_camera, U+E412
    inline constexpr char Model[] = "\xee\xbf\x89"; // view_in_ar, U+EFC9
    inline constexpr char Texture[] = "\xee\x8f\xb4"; // image, U+E3F4
    inline constexpr char Material[] = "\xee\x90\xa1"; // texture, U+E421
    inline constexpr char Terrain[] = "\xee\x95\xa4"; // terrain, U+E564
    inline constexpr char Shader[] = "\xef\xa1\x8d"; // code_blocks, U+F84D
    inline constexpr char Script[] = "\xee\xa1\xaf"; // code, U+E86F
    inline constexpr char HDR[] = "\xee\x9a\x91"; // panorama, U+E691
    inline constexpr char Volume[] = "\xee\x90\xa9"; // tune, U+E429
    inline constexpr char Font[] = "\xee\x89\xa2"; // text_fields, U+E262
    inline constexpr char Unknown[] = "\xee\x99\xad"; // draft, U+E66D
    inline constexpr char Menu[] = "\xee\x97\x92"; // menu, U+E5D2
    inline constexpr char World[] = "\xee\xa8\x87"; // language, U+EA07
    inline constexpr char Lit[] = "\xee\xac\xb7"; // contrast, U+EB37
    inline constexpr char Show[] = "\xee\xa3\xb4"; // visibility, U+E8F4
    inline constexpr char Lock[] = "\xee\xa2\x99"; // lock, U+E899
    inline constexpr char Unlock[] = "\xee\xa2\x98"; // lock_open, U+E898

    struct Role { const char* name; const char* symbol; unsigned int codepoint; };
    inline constexpr Role Roles[] = {
        { "Scene", "view_in_ar", 0xefc9 },
        { "Game", "sports_esports", 0xea28 },
        { "Hierarchy", "account_tree", 0xe97a },
        { "Inspector", "tune", 0xe429 },
        { "AssetBundle", "inventory_2", 0xe1a1 },
        { "ContentBrowser", "folder_open", 0xe2c8 },
        { "Select", "arrow_selector_tool", 0xf82f },
        { "Move", "open_with", 0xe89f },
        { "Rotate", "rotate_right", 0xe41a },
        { "Scale", "open_in_full", 0xf1ce },
        { "Orthographic", "crop_square", 0xe3c6 },
        { "Perspective", "view_in_ar", 0xefc9 },
        { "Grid", "grid_4x4", 0xf016 },
        { "Snap", "grid_on", 0xe3ec },
        { "Search", "search", 0xef7a },
        { "Settings", "settings", 0xe8b8 },
        { "AvatarMask", "accessibility_new", 0xe92c },
        { "Add", "add", 0xe145 },
        { "Remove", "remove", 0xe15b },
        { "Delete", "delete", 0xe92e },
        { "Folder", "folder", 0xe2c7 },
        { "GameObject", "deployed_code", 0xf720 },
        { "Prefab", "deployed_code", 0xf720 },
        { "AssetPicker", "folder_open", 0xe2c8 },
        { "More", "more_horiz", 0xe5d3 },
        { "Back", "arrow_back", 0xe5c4 },
        { "Forward", "arrow_forward", 0xe5c8 },
        { "Up", "arrow_upward", 0xe5d8 },
        { "Down", "arrow_downward", 0xe5db },
        { "Audio", "audio_file", 0xeb82 },
        { "Play", "play_arrow", 0xe037 },
        { "Pause", "pause", 0xe034 },
        { "Stop", "stop", 0xe047 },
        { "Debug", "bug_report", 0xe868 },
        { "Console", "terminal", 0xeb8e },
        { "Profiler", "bar_chart", 0xe26b },
        { "Info", "info", 0xe88e },
        { "Warning", "warning", 0xf083 },
        { "Error", "error", 0xf8b6 },
        { "Revert", "undo", 0xe166 },
        { "Runtime", "memory", 0xe322 },
        { "Layers", "layers", 0xe53b },
        { "Tag", "sell", 0xf05b },
        { "Timing", "timer", 0xe425 },
        { "Baseline", "flag", 0xf0c6 },
        { "Close", "close", 0xe5cd },
        { "Expand", "expand_more", 0xe5cf },
        { "Collapse", "chevron_right", 0xe5cc },
        { "Appearance", "brush", 0xe3ae },
        { "Camera", "photo_camera", 0xe412 },
        { "Model", "view_in_ar", 0xefc9 },
        { "Texture", "image", 0xe3f4 },
        { "Material", "texture", 0xe421 },
        { "Terrain", "terrain", 0xe564 },
        { "Shader", "code_blocks", 0xf84d },
        { "Script", "code", 0xe86f },
        { "HDR", "panorama", 0xe691 },
        { "Volume", "tune", 0xe429 },
        { "Font", "text_fields", 0xe262 },
        { "Unknown", "draft", 0xe66d },
        { "Menu", "menu", 0xe5d2 },
        { "World", "language", 0xea07 },
        { "Lit", "contrast", 0xeb37 },
        { "Show", "visibility", 0xe8f4 },
        { "Lock", "lock", 0xe899 },
        { "Unlock", "lock_open", 0xe898 },
    };

    // Static storage: composed labels never point into a temporary string.
    template<std::size_t N> struct Text
    {
        char value[N]{};
        consteval Text(const char (&text)[N])
        {
            for (std::size_t i = 0; i < N; ++i) value[i] = text[i];
        }
    };
    template<const auto& Icon, Text Suffix>
    inline constexpr auto LabelStorage = []
    {
        std::array<char, sizeof(Icon) + sizeof(Suffix.value) - 1> result{};
        for (std::size_t i = 0; i + 1 < sizeof(Icon); ++i) result[i] = Icon[i];
        for (std::size_t i = 0; i < sizeof(Suffix.value); ++i)
            result[sizeof(Icon) - 1 + i] = Suffix.value[i];
        return result;
    }();
    template<const auto& Icon, Text Suffix>
    inline constexpr const char* Label = LabelStorage<Icon, Suffix>.data();
}
