param(
    [string]$Repository = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
    [string]$ClangFormat = 'C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/Llvm/x64/bin/clang-format.exe'
)

$ErrorActionPreference = 'Stop'
if (-not (Test-Path -LiteralPath $ClangFormat)) { throw 'clang-format is required for CreatorEngine formatting' }
$fixturePath = Join-Path $Repository 'Tools/LatticeExample/fixtures/blender-5.1.1-shader-nodes.json'
$fixture = Get-Content -LiteralPath $fixturePath -Raw | ConvertFrom-Json
if ($fixture.blender_version -ne '5.1.1' -or $fixture.blender_build_hash -ne 'b70da489d7f4')
{
    throw 'Unexpected Blender schema fixture'
}

$nodeTypes = @('ShaderNodeRGB', 'ShaderNodeValue', 'ShaderNodeTexImage', 'ShaderNodeNormalMap',
               'ShaderNodeBsdfPrincipled', 'ShaderNodeOutputMaterial')
$source = [System.Text.StringBuilder]::new()
[void]$source.AppendLine(@'
// Generated by Tools/blender/export-lx-material-schema.ps1 from the pinned Blender 5.1.1 socket fixture.
#include "LXMaterialOperators.h"

#include <stdexcept>

namespace LX
{
namespace
{
void Register(LXMaterialDefinitions& result, LXNodeDefinitionRegistry& registry, NodeSpec spec,
              LXMaterialNodeSchema schema)
{
    const auto type = spec.type;
    std::string error;
    if (!registry.Register({"material", std::move(spec)}, &error))
    {
        throw std::logic_error(error);
    }
    result.schemas.emplace(type, std::move(schema));
}
} // namespace

LXMaterialDefinitions CreateMaterialDefinitions()
{
    LXMaterialDefinitions result;
    auto registry = std::make_shared<LXNodeDefinitionRegistry>();
'@)

function CppString([string]$value)
{
    return ConvertTo-Json -InputObject $value -Compress
}

function CppNumber($value)
{
    $text = ([double]$value).ToString('R', [System.Globalization.CultureInfo]::InvariantCulture)
    if ($text -notmatch '[.Ee]') { $text += '.0' }
    return $text
}

foreach ($type in $nodeTypes)
{
    $node = $fixture.nodes | Where-Object type -eq $type
    if (@($node).Count -ne 1) { throw "Missing node $type" }
    [void]$source.AppendLine('    {')
    [void]$source.AppendLine('        NodeSpec spec;')
    [void]$source.AppendLine("        spec.type = $(CppString $type);")
    [void]$source.AppendLine("        spec.title = $(CppString $node.label);")
    [void]$source.AppendLine('        LXMaterialNodeSchema schema;')
    foreach ($direction in @('Input','Output'))
    {
        $sockets = if ($direction -eq 'Input') { $node.inputs } else { $node.outputs }
        foreach ($socket in $sockets)
        {
            $pinType = switch -Regex ($socket.type)
            {
                '^NodeSocketFloat' { 'Float'; break }
                '^NodeSocketVector' { 'Vector'; break }
                '^NodeSocketColor' { 'Color'; break }
                '^NodeSocketShader' { 'Closure'; break }
                default { throw "Unsupported fixture socket $($socket.type)" }
            }
            $value = '{}'
            if ($null -ne $socket.default)
            {
                if ($pinType -in @('Vector','Color'))
                {
                    $components = ($socket.default | ForEach-Object { CppNumber $_ }) -join ', '
                    $value = "std::array<double, $(@($socket.default).Count)>{$components}"
                }
                else { $value = CppNumber $socket.default }
            }
            $enabled = $socket.enabled.ToString().ToLowerInvariant()
            $hidden = $socket.hidden.ToString().ToLowerInvariant()
            $hideValue = $socket.hide_value.ToString().ToLowerInvariant()
            $multiple = $socket.multi_input.ToString().ToLowerInvariant()
            $space = if ($pinType -eq 'Color') { 'Linear' } else { 'Data' }
            [void]$source.AppendLine("        spec.pins.push_back({0, 0, $(CppString $socket.name), Direction::$direction, PinType::$pinType,")
            [void]$source.AppendLine("                              $multiple, false, $(CppString $socket.identifier), $value});")
            [void]$source.AppendLine("        schema.sockets.push_back({$enabled, $hidden, $hideValue, LXColorSpace::$space});")
        }
    }
    if ($type -eq 'ShaderNodeTexImage')
    {
        [void]$source.AppendLine('        spec.properties = {{"image", ""}, {"colorSpace", "srgb"}, {"interpolation", "Linear"}, {"extension", "REPEAT"}, {"projection", "FLAT"}};')
        [void]$source.AppendLine('        schema.enumProperties = {{"colorSpace", {"data", "linear", "srgb"}}, {"interpolation", {"Linear", "Closest", "Cubic", "Smart"}}, {"extension", {"REPEAT", "EXTEND", "CLIP", "MIRROR"}}, {"projection", {"FLAT", "BOX", "SPHERE", "TUBE"}}};')
    }
    if ($type -eq 'ShaderNodeNormalMap')
    {
        [void]$source.AppendLine('        spec.properties = {{"space", "TANGENT"}, {"uvMap", ""}};')
        [void]$source.AppendLine('        schema.enumProperties = {{"space", {"TANGENT", "OBJECT", "WORLD", "BLENDER_OBJECT", "BLENDER_WORLD"}}};')
    }
    if ($type -eq 'ShaderNodeOutputMaterial')
    {
        [void]$source.AppendLine('        spec.properties = {{"target", "ALL"}};')
        [void]$source.AppendLine('        schema.enumProperties = {{"target", {"ALL", "EEVEE", "CYCLES"}}};')
    }
    [void]$source.AppendLine('        Register(result, *registry, std::move(spec), std::move(schema));')
    [void]$source.AppendLine('    }')
}

[void]$source.AppendLine(@'
    // Engine resource/parameter primitives. These are not presented as Blender node definitions.
    for (PinType type : {PinType::Bool, PinType::Int, PinType::Float, PinType::Vector, PinType::Color,
                         PinType::Normal, PinType::Texture, PinType::Sampler})
    {
        NodeSpec spec;
        spec.type = std::string("LXParameter") + PinTypeName(type);
        spec.title = std::string(PinTypeName(type)) + " Parameter";
        spec.pins.push_back({0, 0, "Value", Direction::Output, type, false, false, "Value"});
        spec.properties = {{"parameter", "0"}};
        LXMaterialNodeSchema schema;
        schema.sockets.push_back({true, false, false, type == PinType::Color ? LXColorSpace::Linear : LXColorSpace::Data});
        NodeSpec reroute;
        reroute.type = std::string("LXReroute") + PinTypeName(type);
        reroute.title = "Reroute";
        reroute.pins = {{0, 0, "Input", Direction::Input, type, false, false, "Input"},
                       {0, 0, "Output", Direction::Output, type, false, false, "Output"}};
        LXMaterialNodeSchema rerouteSchema;
        rerouteSchema.sockets = {schema.sockets.front(), schema.sockets.front()};
        Register(result, *registry, std::move(spec), std::move(schema));
        Register(result, *registry, std::move(reroute), std::move(rerouteSchema));
    }
    RegisterMaterialOperators(result, *registry);
    result.nodes = std::move(registry);
    return result;
}

} // namespace LX
'@)

$outputPath = Join-Path $Repository 'Lattice/Material/LXMaterialNodes.cpp'
[System.IO.File]::WriteAllText($outputPath, $source.ToString(), [System.Text.UTF8Encoding]::new($false))
& $ClangFormat -i $outputPath
if ($LASTEXITCODE -ne 0) { throw 'Generated Material schema formatting failed' }
