"""Generate pinned Fourier CMF coefficients for linear Rec.709, offline.

XYZ data: Blender Foundation, Apache-2.0. See the fixture NOTICE.md.
"""
import argparse
import csv
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIXTURE = ROOT / 'Tools/blender/fixtures/thin-film-sensitivity-5.1.1'
INPUT_HASH = '687e8ac2481fc52fe4bdc6c90eceba1ccb3794a5bda5a26d09b5fe543d0467d4'
MATRIX = ((3.2404542, -1.5371385, -.4985314),
          (-.9692660, 1.8760108, .0415560),
          (.0556434, -.2040259, 1.0572252))


def generated():
    source = (FIXTURE / 'cie-fourier.csv').read_bytes()
    if hashlib.sha256(source).hexdigest() != INPUT_HASH:
        raise ValueError('Pinned Cycles Fourier CMF identity differs')
    rows = [list(map(float, row)) for row in list(csv.reader(source.decode().splitlines()))[1:]]
    if len(rows) != 512 or any(len(row) != 6 for row in rows):
        raise ValueError('Expected 512 complex XYZ entries')
    dc = [sum(a * b for a, b in zip(matrix, rows[0][:3])) for matrix in MATRIX]
    rgb = [[sum(a * b for a, b in zip(matrix, row[start:start + 3])) / dc[channel]
            for start in (0, 3) for channel, matrix in enumerate(MATRIX)] for row in rows]
    notice = '// Generated by Tools/blender/generate-thin-film-sensitivity.py.\n' \
             '// XYZ CMF data: Copyright 2011-2025 Blender Foundation, Apache-2.0.\n' \
             '// See Tools/blender/fixtures/thin-film-sensitivity-5.1.1/NOTICE.md.\n'
    shader = '#pragma once\n' + notice
    for name, start in (('FilmSensitivityReal', 0), ('FilmSensitivityImag', 3)):
        shader += f'static const float3 {name}[512] = {{\n'
        shader += ''.join('    float3(' + ', '.join(f'{x:.9e}' for x in row[start:start + 3]) + '),\n'
                          for row in rgb)
        shader += '};\n'
    header = '#pragma once\n#include <array>\n' + notice
    header += 'inline constexpr std::array<std::array<double, 6>, 512> kFilmSensitivity{{\n'
    header += ''.join('    {{' + ', '.join(f'{x:.17e}' for x in row) + '}},\n' for row in rgb)
    header += '}};\n'
    return {ROOT / 'Dynamic_CPP/Assets/Shaders/DefaultPassShader/Includes/PrincipledThinFilmSensitivity.slang': shader,
            ROOT / 'Tools/regression/principled_thin_film_sensitivity.h': header}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in generated().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding='utf-8') != content:
                raise ValueError(f'Generated sensitivity differs: {path}')
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    print('THIN_FILM_SENSITIVITY_OK entries=512 colorSpace=linear-rec709')


if __name__ == '__main__':
    main()
